name: fastapi application test

on:
  push:
    branches: [master]
  pull_request:
    branches: [fastapi]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.ETA_OPENAI_KEY }}

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run pytest
        run: |
          cd tests
          pytest
